/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedOrganizerDashboardRouteImport } from './routes/_protected/organizer/dashboard'
import { Route as ProtectedAttendeeInviteRouteImport } from './routes/_protected/attendee/invite'
import { Route as ProtectedOrganizerEventEventIdRouteImport } from './routes/_protected/organizer/event.$eventId'
import { Route as ProtectedAttendeeEventEventIdProfileIdRouteImport } from './routes/_protected/attendee/event.$eventId.$profileId'

const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOrganizerDashboardRoute =
  ProtectedOrganizerDashboardRouteImport.update({
    id: '/organizer/dashboard',
    path: '/organizer/dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAttendeeInviteRoute = ProtectedAttendeeInviteRouteImport.update({
  id: '/attendee/invite',
  path: '/attendee/invite',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizerEventEventIdRoute =
  ProtectedOrganizerEventEventIdRouteImport.update({
    id: '/organizer/event/$eventId',
    path: '/organizer/event/$eventId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAttendeeEventEventIdProfileIdRoute =
  ProtectedAttendeeEventEventIdProfileIdRouteImport.update({
    id: '/attendee/event/$eventId/$profileId',
    path: '/attendee/event/$eventId/$profileId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/health': typeof HealthRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/attendee/invite': typeof ProtectedAttendeeInviteRoute
  '/organizer/dashboard': typeof ProtectedOrganizerDashboardRoute
  '/organizer/event/$eventId': typeof ProtectedOrganizerEventEventIdRoute
  '/attendee/event/$eventId/$profileId': typeof ProtectedAttendeeEventEventIdProfileIdRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof ProtectedIndexRoute
  '/attendee/invite': typeof ProtectedAttendeeInviteRoute
  '/organizer/dashboard': typeof ProtectedOrganizerDashboardRoute
  '/organizer/event/$eventId': typeof ProtectedOrganizerEventEventIdRoute
  '/attendee/event/$eventId/$profileId': typeof ProtectedAttendeeEventEventIdProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/health': typeof HealthRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/attendee/invite': typeof ProtectedAttendeeInviteRoute
  '/_protected/organizer/dashboard': typeof ProtectedOrganizerDashboardRoute
  '/_protected/organizer/event/$eventId': typeof ProtectedOrganizerEventEventIdRoute
  '/_protected/attendee/event/$eventId/$profileId': typeof ProtectedAttendeeEventEventIdProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/signup'
    | '/attendee/invite'
    | '/organizer/dashboard'
    | '/organizer/event/$eventId'
    | '/attendee/event/$eventId/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/login'
    | '/signup'
    | '/'
    | '/attendee/invite'
    | '/organizer/dashboard'
    | '/organizer/event/$eventId'
    | '/attendee/event/$eventId/$profileId'
  id:
    | '__root__'
    | '/_protected'
    | '/health'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/'
    | '/_protected/attendee/invite'
    | '/_protected/organizer/dashboard'
    | '/_protected/organizer/event/$eventId'
    | '/_protected/attendee/event/$eventId/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  HealthRoute: typeof HealthRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/organizer/dashboard': {
      id: '/_protected/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof ProtectedOrganizerDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/attendee/invite': {
      id: '/_protected/attendee/invite'
      path: '/attendee/invite'
      fullPath: '/attendee/invite'
      preLoaderRoute: typeof ProtectedAttendeeInviteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizer/event/$eventId': {
      id: '/_protected/organizer/event/$eventId'
      path: '/organizer/event/$eventId'
      fullPath: '/organizer/event/$eventId'
      preLoaderRoute: typeof ProtectedOrganizerEventEventIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/attendee/event/$eventId/$profileId': {
      id: '/_protected/attendee/event/$eventId/$profileId'
      path: '/attendee/event/$eventId/$profileId'
      fullPath: '/attendee/event/$eventId/$profileId'
      preLoaderRoute: typeof ProtectedAttendeeEventEventIdProfileIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAttendeeInviteRoute: typeof ProtectedAttendeeInviteRoute
  ProtectedOrganizerDashboardRoute: typeof ProtectedOrganizerDashboardRoute
  ProtectedOrganizerEventEventIdRoute: typeof ProtectedOrganizerEventEventIdRoute
  ProtectedAttendeeEventEventIdProfileIdRoute: typeof ProtectedAttendeeEventEventIdProfileIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAttendeeInviteRoute: ProtectedAttendeeInviteRoute,
  ProtectedOrganizerDashboardRoute: ProtectedOrganizerDashboardRoute,
  ProtectedOrganizerEventEventIdRoute: ProtectedOrganizerEventEventIdRoute,
  ProtectedAttendeeEventEventIdProfileIdRoute:
    ProtectedAttendeeEventEventIdProfileIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  HealthRoute: HealthRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
